//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public string AdminUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Password { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostalCode { get; set; }
        public string AreasOfExpertise { get; set; }
        public Nullable<int> AdminUserType { get; set; }
        public Nullable<int> IsSystemAdministrator { get; set; }
        public Nullable<int> IsReceivesPastDueNoFixNotifications { get; set; }
        public Nullable<int> Market { get; set; }
        public string Permissions { get; set; }
        public Nullable<double> ValidationPayRateDollarsPerHour { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string UpdatedDateTimeUTC { get; set; }
        public string CreatedDateTimeUTC { get; set; }
        public string LastLoginDateTimeUTC { get; set; }
        public string PropertyDefinitionDataSetId { get; set; }
        public Nullable<int> EnablePropertyDefinitionEditingOnForms { get; set; }
    }
}
