//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class innovadev01Entities : DbContext
    {
        public innovadev01Entities()
            : base("name=innovadev01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DiagnosticReport> DiagnosticReports { get; set; }
        public DbSet<ExternalSystem> ExternalSystems { get; set; }
        public DbSet<PolkVehicleYMME> PolkVehicleYMMEs { get; set; }
        public DbSet<TSB> TSBs { get; set; }
        public DbSet<TSBAAIAToLegacyVehicleID> TSBAAIAToLegacyVehicleIDs { get; set; }
        public DbSet<TSBToVehicle> TSBToVehicles { get; set; }
        public DbSet<Recall> Recalls { get; set; }
        public DbSet<Recall_ByCleanModel> Recall_ByCleanModel { get; set; }
        public DbSet<DiagnosticReportExternalSystemReportId> DiagnosticReportExternalSystemReportIds { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
        public DbSet<DTCCodeLaymanTerm> DTCCodeLaymanTerms { get; set; }
        public DbSet<DTCCodeLaymanTermSeverityDefinition> DTCCodeLaymanTermSeverityDefinitions { get; set; }
        public DbSet<DLCLocation> DLCLocations { get; set; }
    }
}
