//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticReportExternalSystemReportId
    {
        public int Id { get; set; }
        public string DiagnosticReportId { get; set; }
        public string ExternalSystemReportId { get; set; }
    }
}
