//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLCLocation
    {
        public string DlcLocationId { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> LocationNumber { get; set; }
        public string Access { get; set; }
        public string Access_French { get; set; }
        public string Access_Spanish { get; set; }
        public string Comments { get; set; }
        public string Comments_French { get; set; }
        public string Comments_Spanish { get; set; }
        public string ImageFileName { get; set; }
    }
}
