//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTCCodeLaymanTerm
    {
        public int DTCCodeLaymanTermId { get; set; }
        public string ErrorCode { get; set; }
        public string Make { get; set; }
        public string Title { get; set; }
        public string Title_es { get; set; }
        public string Title_fr { get; set; }
        public string Title_zh { get; set; }
        public string Description { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_zh { get; set; }
        public int SeverityLevel { get; set; }
        public string EffectOnVehicle { get; set; }
        public string EffectOnVehicle_es { get; set; }
        public string EffectOnVehicle_fr { get; set; }
        public string EffectOnVehicle_zh { get; set; }
        public string ResponsibleComponentOrSystem { get; set; }
        public string ResponsibleComponentOrSystem_es { get; set; }
        public string ResponsibleComponentOrSystem_fr { get; set; }
        public string ResponsibleComponentOrSystem_zh { get; set; }
        public string WhyItsImportant { get; set; }
        public string WhyItsImportant_es { get; set; }
        public string WhyItsImportant_fr { get; set; }
        public string WhyItsImportant_zh { get; set; }
    }
}
