//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolkVehicleYMME
    {
        public string PolkVehicleYMMEId { get; set; }
        public string VinPatternMask { get; set; }
        public string DlcLocationId { get; set; }
        public string VehicleClass { get; set; }
        public string VehicleClass2 { get; set; }
        public string VehicleClass3 { get; set; }
        public string Manufacturer { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string Trim { get; set; }
        public string EngineVinCode { get; set; }
        public string EngineType { get; set; }
        public string AAIA { get; set; }
        public string Transmission { get; set; }
        public Nullable<int> BaseMSRP { get; set; }
        public string ModelImageName { get; set; }
        public string TrimImageName { get; set; }
        public string CrashRating { get; set; }
        public Nullable<decimal> CurrentMarketValue { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<decimal> FuelMPGCombined { get; set; }
        public Nullable<decimal> FuelMPGCity { get; set; }
        public Nullable<decimal> FuelMPGHighway { get; set; }
        public Nullable<int> ACESBaseVehicleID { get; set; }
        public Nullable<int> ACESBodyStyleConfigID { get; set; }
        public Nullable<int> ACESBodyTypeID { get; set; }
        public string ACESBodyTypeName { get; set; }
        public Nullable<int> ACESEngineBaseID { get; set; }
        public Nullable<int> ACESEngineConfigID { get; set; }
        public Nullable<int> ACESEngineDestinationID { get; set; }
        public Nullable<int> ACESEngineVinID { get; set; }
        public Nullable<int> ACESMakeID { get; set; }
        public Nullable<int> ACESModelID { get; set; }
        public Nullable<int> ACESSubModelID { get; set; }
        public Nullable<int> ACESVehicleEngineConfigID { get; set; }
        public string ACESVehicleTypeName { get; set; }
        public Nullable<int> ACESVehicleTypeID { get; set; }
        public Nullable<int> ACESYearID { get; set; }
        public string PowertrainEcu { get; set; }
        public Nullable<bool> IsPowertrainEcuId { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public string PrimaryEngineType { get; set; }
        public string BodyStyleDesc { get; set; }
    }
}
