//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recall
    {
        public int RecordNumber { get; set; }
        public string CampaignNumber { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string ManufacturerCampaignNumber { get; set; }
        public string ComponentName { get; set; }
        public string ComponentName_es { get; set; }
        public string ComponentName_fr { get; set; }
        public string ComponentName_zh { get; set; }
        public string ManufacturerText { get; set; }
        public string BeginManufactering { get; set; }
        public string EndManufacturing { get; set; }
        public string RecallTypeCode { get; set; }
        public string PotAff { get; set; }
        public string ODate { get; set; }
        public string InfluencedBy { get; set; }
        public string ManufacturerName { get; set; }
        public string RecallDate { get; set; }
        public string DateA { get; set; }
        public string RPNO { get; set; }
        public string FMVSS { get; set; }
        public string DefectDescription { get; set; }
        public string DefectDescription_es { get; set; }
        public string DefectDescription_fr { get; set; }
        public string DefectDescription_zh { get; set; }
        public string DefectConsequence { get; set; }
        public string DefectConsequence_es { get; set; }
        public string DefectConsequence_fr { get; set; }
        public string DefectConsequence_zh { get; set; }
        public string DefectCorrectiveAction { get; set; }
        public string DefectCorrectiveAction_es { get; set; }
        public string DefectCorrectiveAction_fr { get; set; }
        public string DefectCorrectiveAction_zh { get; set; }
    }
}
