//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSBToVehicle
    {
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> TSBID { get; set; }
        public Nullable<int> BaseVehicleID { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public int id { get; set; }
    }
}
