//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppForm
    {
        public int FormId { get; set; }
        public string FormName { get; set; }
        public string FormURL { get; set; }
        public Nullable<bool> IsMenuHeading { get; set; }
        public Nullable<int> ParentMenuId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DisplayName { get; set; }
        public int Level { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public int Order { get; set; }
        public Nullable<bool> IsInternalPage { get; set; }
    }
}
