//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoZoneStore
    {
        public int StoreNbr { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Telephone { get; set; }
        public string StoreManager { get; set; }
        public string WarehouseNbr { get; set; }
        public string Warehouse { get; set; }
        public string Region { get; set; }
        public string RegionalManager { get; set; }
        public string DistrictManager { get; set; }
        public string CreatedDate { get; set; }
        public string StoreSizeFT { get; set; }
        public string ClimateCode { get; set; }
        public string ClimateDesc { get; set; }
        public string Market { get; set; }
        public string Country { get; set; }
    }
}
