//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarScanSession
    {
        public string CarScanSessionId { get; set; }
        public string KioskId { get; set; }
        public string UserId { get; set; }
        public long DiagnosticReportId { get; set; }
        public string OrderId { get; set; }
        public string CarScanDiagnosticReportNumber { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ZipCode { get; set; }
        public string CC { get; set; }
        public string CCType { get; set; }
        public Nullable<int> CCExMnth { get; set; }
        public Nullable<int> CCExYear { get; set; }
        public string CCAuthRefId { get; set; }
        public string CCAuthCode { get; set; }
        public Nullable<decimal> CCAuthAmount { get; set; }
        public string CCAuthVoidRefId { get; set; }
        public Nullable<System.DateTime> CheckOutDateTimeUTC { get; set; }
        public string ToolId { get; set; }
        public Nullable<System.DateTime> CheckInDateTimeUTC { get; set; }
        public string KioskId_CheckIn { get; set; }
        public string rawUploadString { get; set; }
        public Nullable<System.DateTime> CheckInFailAutoCheckInDateTimeUTC { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
    }
}
