//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class changelog
    {
        public int id { get; set; }
        public Nullable<sbyte> type { get; set; }
        public string version { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public string checksum { get; set; }
        public string installed_by { get; set; }
        public System.DateTime installed_on { get; set; }
        public bool success { get; set; }
    }
}
