//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string CountryId { get; set; }
        public string Name { get; set; }
        public string NumericCode { get; set; }
        public string LongAlphaCode { get; set; }
        public string ShortAlphaCode { get; set; }
        public string IsoCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
