//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchangeRate
    {
        public string CurrencyExchangeRateId { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyISOCode { get; set; }
        public decimal ExchangeRatePerUSD { get; set; }
        public System.DateTime EffectiveDateTimeUTC { get; set; }
    }
}
