//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticReportResultFix
    {
        public string DiagnosticReportResultFixId { get; set; }
        public string DiagnosticReportResultId { get; set; }
        public string FixNameId { get; set; }
        public string FixId { get; set; }
        public string OrderLineItemId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Name { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_zh { get; set; }
        public string Description { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_zh { get; set; }
        public string PrimaryErrorCode { get; set; }
        public Nullable<int> DiagnosticReportErrorCodeSystemType { get; set; }
        public Nullable<decimal> Labor { get; set; }
        public Nullable<decimal> LaborRate { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> LaborRateInLocalCurrency { get; set; }
        public Nullable<decimal> LaborCostInLocalCurrency { get; set; }
        public Nullable<decimal> AdditionalCost { get; set; }
        public Nullable<decimal> AdditionalCostInLocalCurrency { get; set; }
        public Nullable<int> FrequencyCount { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> TotalCostInLocalCurrency { get; set; }
        public Nullable<decimal> PartsCost { get; set; }
        public Nullable<decimal> PartsCostInLocalCurrency { get; set; }
        public Nullable<bool> DiagnosticReportIsExactMatch { get; set; }
        public Nullable<int> DiagnosticReportSecondaryCodeAssignmentMatches { get; set; }
        public Nullable<bool> IsFromPolkMatch { get; set; }
        public Nullable<bool> IsFromVinPowerMatch { get; set; }
    }
}
