//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticReportFeedback
    {
        public string DiagnosticReportFeedbackId { get; set; }
        public long DiagnosticReportId { get; set; }
        public string FixId { get; set; }
        public string UploadedFilesFolderId { get; set; }
        public Nullable<int> RepairedByType { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
    }
}
