//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticReportResultErrorCode
    {
        public string DiagnosticReportResultErrorCodeId { get; set; }
        public string DiagnosticReportResultId { get; set; }
        public string VehicleTypeCodeId { get; set; }
        public string DtcCodeId { get; set; }
        public string DtcMasterCodeListId { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorCodeType { get; set; }
        public Nullable<int> DiagnosticReportErrorCodeType { get; set; }
        public Nullable<int> DiagnosticReportErrorCodeSystemType { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> UnableToFindCodeData { get; set; }
        public Nullable<int> VehicleTypeCodeCodeId { get; set; }
        public string VehicleTypeCodeTitle { get; set; }
        public string VehicleTypeCodeConditions { get; set; }
        public string VehicleTypeCodePossibleCauses { get; set; }
        public Nullable<int> VehicleTypeCodeTrips { get; set; }
        public string VehicleTypeCodeMessageIndicatorLampFile { get; set; }
        public string VehicleTypeCodeTransmissionControlIndicatorLampFile { get; set; }
        public string VehicleTypeCodePassiveAntiTheftIndicatorLampFile { get; set; }
        public string VehicleTypeCodeServiceThrottleSoonIndicatorLampFile { get; set; }
        public string VehicleTypeCodeMonitorType { get; set; }
        public string VehicleTypeCodeMonitorFile { get; set; }
        public Nullable<bool> VehicleTypeCodeIsDelmarCode { get; set; }
        public Nullable<int> VehicleTypeCodeStatus { get; set; }
        public string DtcCodeTitle { get; set; }
        public string DtcCodePossibleCauses { get; set; }
        public Nullable<int> DtcCodeFrequencyCount { get; set; }
        public Nullable<int> DtcCodeTrips { get; set; }
        public string DtcCodeMessageIndicatorLampFile { get; set; }
        public string DtcCodeTransmissionControlIndicatorLampFile { get; set; }
        public string DtcCodePassiveAntiTheftIndicatorLampFile { get; set; }
        public string DtcCodeServiceThrottleSoonIndicatorLampFile { get; set; }
        public string DtcCodeMonitorType { get; set; }
        public string DtcCodeMonitorFile { get; set; }
        public string DtcMasterCodeListTitle { get; set; }
        public string DtcMasterCodeListTitle_Spanish { get; set; }
        public string DtcMasterCodeListTitle_French { get; set; }
        public string VehicleTypeCodeTitle_es { get; set; }
        public string VehicleTypeCodeTitle_fr { get; set; }
        public string VehicleTypeCodeTitle_zh { get; set; }
        public string VehicleTypeCodeConditions_es { get; set; }
        public string VehicleTypeCodeConditions_fr { get; set; }
        public string VehicleTypeCodeConditions_zh { get; set; }
        public string VehicleTypeCodePossibleCauses_es { get; set; }
        public string VehicleTypeCodePossibleCauses_fr { get; set; }
        public string VehicleTypeCodePossibleCauses_zh { get; set; }
        public string DtcCodeTitle_es { get; set; }
        public string DtcCodeTitle_fr { get; set; }
        public string DtcCodeTitle_zh { get; set; }
        public string DtcCodeConditions { get; set; }
        public string DtcCodeConditions_es { get; set; }
        public string DtcCodeConditions_fr { get; set; }
        public string DtcCodeConditions_zh { get; set; }
        public string DtcCodePossibleCauses_es { get; set; }
        public string DtcCodePossibleCauses_fr { get; set; }
        public string DtcCodePossibleCauses_zh { get; set; }
    }
}
