//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticReportFixFeedbackPart
    {
        public string DiagnosticReportFixFeedbackPartId { get; set; }
        public string DiagnosticReportFixFeedbackId { get; set; }
        public string PartName { get; set; }
        public string PartNumber { get; set; }
    }
}
