//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticReportFixFeedback
    {
        public string DiagnosticReportFixFeedbackId { get; set; }
        public long DiagnosticReportId { get; set; }
        public Nullable<bool> IsReportValid { get; set; }
        public string CouldNotFixReason { get; set; }
        public string PrimaryErrorCode { get; set; }
        public Nullable<int> DiagnosticReportErrorCodeSystemType { get; set; }
        public Nullable<int> DiagnosticReportFixFeedbackStatus { get; set; }
        public string UserId_FeedbackProvidedBy { get; set; }
        public string UserId_FeedbackReviewedBy { get; set; }
        public string AdminUserId_FeedbackReviewedBy { get; set; }
        public string FixId { get; set; }
        public Nullable<int> AverageDiagnosticTime { get; set; }
        public Nullable<int> FrequencyEncountered { get; set; }
        public Nullable<int> FixDifficultyRating { get; set; }
        public string ObdFixId { get; set; }
        public string ErrorCodesThatApply { get; set; }
        public string TechComments { get; set; }
        public string BasicToolsRequired { get; set; }
        public string SpecialtyToolsRequired { get; set; }
        public string TipsAndTricks { get; set; }
        public string ReviewerComments { get; set; }
        public Nullable<System.DateTime> FeedbackReviewedDateTimeUTC { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> IsPaymentDtcAllowed { get; set; }
        public Nullable<bool> IsPaymentToolsRequiredAllowed { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDateTimeUTC { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
        public string ProRSFixId { get; set; }
    }
}
