//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTCCodeLaymanTermSeverityDefinition
    {
        public int SeverityLevel { get; set; }
        public string SeverityDefinition { get; set; }
        public string SeverityDefinition_es { get; set; }
        public string SeverityDefinition_fr { get; set; }
        public string SeverityDefinition_zh { get; set; }
    }
}
