//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTCMasterCodeList
    {
        public string DTCMasterCodeId { get; set; }
        public string ManufacturerName { get; set; }
        public string MakeString { get; set; }
        public string ErrorCode { get; set; }
        public string Title { get; set; }
        public string Title_Spanish { get; set; }
        public string Title_French { get; set; }
        public Nullable<bool> HasMakeDefined { get; set; }
    }
}
