//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalSystem
    {
        public string ExternalSystemId { get; set; }
        public string KeyGuid { get; set; }
        public string Name { get; set; }
        public string PartnerID { get; set; }
        public string ImageNameSuffix { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> FixPriority { get; set; }
        public string AdminUserCreatedId { get; set; }
        public string AdminUserUpdatedId { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
    }
}
