//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fix
    {
        public string FixId { get; set; }
        public string ObdFixId { get; set; }
        public string FixNameId { get; set; }
        public Nullable<int> FixType { get; set; }
        public string MarketsString { get; set; }
        public string ManufacturerName { get; set; }
        public string PrimaryErrorCode { get; set; }
        public string SecondaryErrorCode { get; set; }
        public string CreatedByAdminUserId { get; set; }
        public string CreatedByUserId { get; set; }
        public string UpdatedByAdminUserId { get; set; }
        public string ApprovedByAdminUserId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsInitiallyReviewed { get; set; }
        public Nullable<bool> IsManufacturerNameChanged { get; set; }
        public Nullable<System.DateTime> ApprovedDateTimeUTC { get; set; }
        public Nullable<bool> HasEngineTypeDefined { get; set; }
        public string EngineTypesString { get; set; }
        public Nullable<bool> HasEngineVINCodeDefined { get; set; }
        public string EngineVINCodesString { get; set; }
        public Nullable<bool> HasYearDefined { get; set; }
        public string YearsString { get; set; }
        public Nullable<bool> HasMakeDefined { get; set; }
        public string MakesString { get; set; }
        public Nullable<bool> HasModelDefined { get; set; }
        public string ModelsString { get; set; }
        public Nullable<bool> HasTrimLevelDefined { get; set; }
        public string TrimLevelsString { get; set; }
        public Nullable<bool> HasTransmissionDefined { get; set; }
        public string TransmissionsString { get; set; }
        public Nullable<bool> HasGenerationDefined { get; set; }
        public string GenerationsString { get; set; }
        public Nullable<bool> HasEngineTypeDefinedPolk { get; set; }
        public string EngineTypesStringPolk { get; set; }
        public Nullable<System.DateTime> EngineTypePolkVerifiedDateTimeUTC { get; set; }
        public Nullable<bool> HasEngineVINCodeDefinedPolk { get; set; }
        public string EngineVINCodesStringPolk { get; set; }
        public Nullable<System.DateTime> EngineVINCodePolkVerifiedDateTimeUTC { get; set; }
        public Nullable<bool> HasYearDefinedPolk { get; set; }
        public string YearsStringPolk { get; set; }
        public Nullable<System.DateTime> YearPolkVerifiedDateTimeUTC { get; set; }
        public Nullable<bool> HasMakeDefinedPolk { get; set; }
        public string MakesStringPolk { get; set; }
        public Nullable<System.DateTime> MakePolkVerifiedDateTimeUTC { get; set; }
        public Nullable<bool> HasModelDefinedPolk { get; set; }
        public string ModelsStringPolk { get; set; }
        public Nullable<System.DateTime> ModelPolkVerifiedDateTimeUTC { get; set; }
        public Nullable<bool> HasTrimLevelDefinedPolk { get; set; }
        public string TrimLevelsStringPolk { get; set; }
        public Nullable<System.DateTime> TrimLevelPolkVerifiedDateTimeUTC { get; set; }
        public string ManufacturerNameVP { get; set; }
        public string EngineTypesStringVP { get; set; }
        public Nullable<bool> HasEngineTypeDefinedVP { get; set; }
        public string EngineVINCodesStringVP { get; set; }
        public Nullable<bool> HasEngineVINCodeDefinedVP { get; set; }
        public string YearsStringVP { get; set; }
        public Nullable<bool> HasYearDefinedVP { get; set; }
        public string MakesStringVP { get; set; }
        public Nullable<bool> HasMakeDefinedVP { get; set; }
        public string ModelsStringVP { get; set; }
        public Nullable<bool> HasModelDefinedVP { get; set; }
        public string TrimLevelsStringVP { get; set; }
        public Nullable<bool> HasTrimLevelDefinedVP { get; set; }
        public string TransmissionsStringVP { get; set; }
        public Nullable<bool> HasTransmissionDefinedVP { get; set; }
        public string Description { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_zh { get; set; }
        public Nullable<decimal> Labor { get; set; }
        public Nullable<decimal> AdditionalCost { get; set; }
        public Nullable<int> FrequencyCount { get; set; }
        public Nullable<bool> NoVehiclesMatch { get; set; }
        public Nullable<System.DateTime> NoVehiclesMatchDateTimeUTC { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
        public string ProRSFixId { get; set; }
    }
}
