//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixComment
    {
        public string FixCommentId { get; set; }
        public string UserId { get; set; }
        public string FixNameId { get; set; }
        public string FixId { get; set; }
        public Nullable<int> FixCommentType { get; set; }
        public string Comment { get; set; }
        public string PrimaryErrorCode { get; set; }
        public Nullable<int> DiagnosticReportErrorCodeSystemType { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string EngineType { get; set; }
        public string EngineVINCode { get; set; }
        public string TrimLevel { get; set; }
        public string Transmission { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
        public string DiagnosticReportId { get; set; }
        public string ParentFixCommentId { get; set; }
        public string DTCCodeId { get; set; }
        public string ErrorCode { get; set; }
        public string CreatedByAdminUserId { get; set; }
        public string UpdatedByAdminUserId { get; set; }
        public string ApprovedByAdminUserId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDateTimeUTC { get; set; }
        public Nullable<bool> HasEngineTypeDefined { get; set; }
        public string EngineTypesString { get; set; }
        public Nullable<bool> HasEngineVINCodeDefined { get; set; }
        public string EngineVINCodesString { get; set; }
        public Nullable<bool> HasYearDefined { get; set; }
        public string YearsString { get; set; }
        public Nullable<bool> HasMakeDefined { get; set; }
        public string MakesString { get; set; }
        public Nullable<bool> HasModelDefined { get; set; }
        public string ModelsString { get; set; }
        public Nullable<bool> HasTrimLevelDefined { get; set; }
        public string TrimLevelsString { get; set; }
        public Nullable<bool> HasTransmissionDefined { get; set; }
        public string TransmissionsString { get; set; }
        public string Title { get; set; }
        public string Title_es { get; set; }
        public string Title_fr { get; set; }
        public string Title_zh { get; set; }
        public string PossibleCauses { get; set; }
        public string PossibleCauses_es { get; set; }
        public string PossibleCauses_fr { get; set; }
        public string PossibleCauses_zh { get; set; }
        public string Conditions { get; set; }
        public string Conditions_es { get; set; }
        public string Conditions_fr { get; set; }
        public string Conditions_zh { get; set; }
        public string TestConditions { get; set; }
        public Nullable<int> FrequencyCount { get; set; }
        public Nullable<int> Trips { get; set; }
        public string MessageIndicatorLampFile { get; set; }
        public string TransmissionControlIndicatorLampFile { get; set; }
        public string PassiveAntiTheftIndicatorLampFile { get; set; }
        public string ServiceThrottleSoonIndicatorLampFile { get; set; }
        public string MonitorType { get; set; }
        public string MonitorFile { get; set; }
    }
}
