//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadByFixAndDtc_View
    {
        public string DiagnosticReportFixFeedbackId { get; set; }
        public long DiagnosticReportId { get; set; }
        public Nullable<bool> IsReportValid { get; set; }
        public string CouldNotFixReason { get; set; }
        public string PrimaryErrorCode { get; set; }
        public string FixId { get; set; }
        public Nullable<int> AverageDiagnosticTime { get; set; }
        public Nullable<int> FrequencyEncountered { get; set; }
        public string ErrorCodesThatApply { get; set; }
        public string TechComments { get; set; }
        public string BasicToolsRequired { get; set; }
        public string SpecialtyToolsRequired { get; set; }
        public string TipsAndTricks { get; set; }
        public string AdminUserId_FeedbackReviewedBy { get; set; }
        public string ObdFixFixId { get; set; }
        public Nullable<int> FixDifficultyRating { get; set; }
    }
}
