//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartOem
    {
        public string PartOemId { get; set; }
        public Nullable<int> AcesBaseVehicleId { get; set; }
        public Nullable<int> AcesEngineBaseId { get; set; }
        public Nullable<int> AcesPartTypeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Retailer { get; set; }
        public string Manufacturer { get; set; }
        public string OemPartNumber { get; set; }
        public string CodemasterID { get; set; }
        public Nullable<int> AcesSubModelId { get; set; }
    }
}
