//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public string PartId { get; set; }
        public string PartNameId { get; set; }
        public string ManufacturerName { get; set; }
        public string MakesString { get; set; }
        public string PartNumber { get; set; }
        public string AdminUserIdCreated { get; set; }
        public string AdminUserIdUpdated { get; set; }
        public string AdminUserIdApproved { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDateTimeUTC { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
    }
}
