//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartName
    {
        public string PartNameId { get; set; }
        public string ACESId { get; set; }
        public string Name { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_zh { get; set; }
        public string AdminUserIdCreated { get; set; }
        public string AdminUserIdUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
    }
}
