//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolkVehicleU
    {
        public string PolkVehicleUSId { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public string VEHICLE_ORIGIN { get; set; }
        public string MAKE { get; set; }
        public string MANUFACTURER { get; set; }
        public string YEAR_MODEL { get; set; }
        public string MODEL { get; set; }
        public string TRIM_LEVEL { get; set; }
        public string GVW { get; set; }
        public string BODY_STYLE { get; set; }
        public string DOOR_COUNT { get; set; }
        public string FUEL_TYPE { get; set; }
        public string CYLINDERS { get; set; }
        public string DISPLACEMENT_CC { get; set; }
        public string DISPLACEMENT_CID { get; set; }
        public string ENGINE_CODE { get; set; }
        public string FUEL_SYSTEM { get; set; }
        public string TURBO_SUPERCHARGED { get; set; }
        public string DRIVE_WHEELS { get; set; }
        public string VEHICLE_SEGMENT { get; set; }
        public string LITERS { get; set; }
        public string VIN_PREFIX { get; set; }
        public string AAIA_CDE { get; set; }
        public string VEH_ID { get; set; }
        public string BASE_VEH_ID { get; set; }
        public string MAKE_ID { get; set; }
        public string MODEL_ID { get; set; }
        public string SUB_MODEL_ID { get; set; }
        public string VEH_TYPE_ID { get; set; }
        public string YEAR_ID { get; set; }
        public string FUEL_TYPE1 { get; set; }
        public string FUEL_DELIVERY { get; set; }
        public string ENGINE_VIN_ID { get; set; }
        public string ASPIRATION_ID { get; set; }
        public string DRIVE_TYPE_ID { get; set; }
        public string BODY_NUM_DOORS_ID { get; set; }
        public string BODY_TYPE_ID { get; set; }
        public string REGION_ID { get; set; }
        public string ACES_LITERS { get; set; }
        public string ACES_CC { get; set; }
        public string ACES_CID { get; set; }
        public string ACES_CYLINDERS { get; set; }
        public string POWER_OUTPUT_ID { get; set; }
        public string FUEL_DEL_CONFIG_ID { get; set; }
        public string BODY_STYLE_CONFIG_ID { get; set; }
        public string VALVES_ID { get; set; }
        public string CYL_HEAD_TYPE_ID { get; set; }
        public string BLOCK_TYPE { get; set; }
        public string ENGINE_BASE_ID { get; set; }
        public string ENGINE_CONFIG_ID { get; set; }
        public string VEH_ENGCONFIG_ID { get; set; }
        public string ENGINE_DESIGNATION_ID { get; set; }
        public Nullable<int> WHOLESALE_AVERAGE { get; set; }
        public Nullable<int> RETAIL_AVERAGE { get; set; }
        public Nullable<int> MSRP { get; set; }
        public string TOTAL { get; set; }
        public string ACES_BLOCK_TYPE { get; set; }
        public string REGISTRATION_CATEGORY { get; set; }
    }
}
