//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolkVehicleUSStatsGrouped
    {
        public string VehicleClass { get; set; }
        public string Manufacturer { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string EngineType { get; set; }
        public string ModelImageFileName { get; set; }
        public string CrashRating { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<decimal> CurrentMarketValue { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<double> PopulationPercentOfTotal { get; set; }
        public Nullable<int> CustomerPopulation { get; set; }
        public Nullable<double> CustomerPopulationPercentOfTotal { get; set; }
        public Nullable<int> RedLightReports { get; set; }
        public Nullable<double> RedLightReportsPercentOfTotal { get; set; }
        public Nullable<int> TSBCount { get; set; }
        public Nullable<double> DistributedRecallCount { get; set; }
        public Nullable<decimal> RepairCost15k { get; set; }
        public Nullable<decimal> RepairCost30k { get; set; }
        public Nullable<decimal> RepairCost45k { get; set; }
        public Nullable<decimal> RepairCost60k { get; set; }
        public Nullable<decimal> RepairCost75k { get; set; }
        public Nullable<decimal> RepairCost90k { get; set; }
        public Nullable<decimal> RepairCost105k { get; set; }
        public Nullable<decimal> MaintenanceCost15k { get; set; }
        public Nullable<decimal> MaintenanceCost30k { get; set; }
        public Nullable<decimal> MaintenanceCost45k { get; set; }
        public Nullable<decimal> MaintenanceCost60k { get; set; }
        public Nullable<decimal> MaintenanceCost75k { get; set; }
        public Nullable<decimal> MaintenanceCost90k { get; set; }
        public Nullable<decimal> MaintenanceCost105k { get; set; }
        public Nullable<decimal> FuelMPGCombined { get; set; }
        public Nullable<decimal> FuelMPGCity { get; set; }
        public Nullable<decimal> FuelMPGHighway { get; set; }
        public Nullable<decimal> InsuranceCost { get; set; }
        public Nullable<decimal> AnnualDepreciationPercent { get; set; }
        public Nullable<int> CrashRatingScore { get; set; }
        public Nullable<decimal> CrashRatingScorePercentile { get; set; }
        public Nullable<double> ReliabilityScore { get; set; }
        public Nullable<decimal> ReliabilityScorePercentile { get; set; }
        public Nullable<double> TSBScore { get; set; }
        public Nullable<decimal> TSBScorePercentile { get; set; }
        public Nullable<double> RecallScore { get; set; }
        public Nullable<decimal> RecallScorePercentile { get; set; }
        public Nullable<double> RepairCostScore { get; set; }
        public Nullable<decimal> RepairCostScorePercentile { get; set; }
        public Nullable<double> MaintenanceScore { get; set; }
        public Nullable<decimal> MaintenanceScorePercentile { get; set; }
        public Nullable<double> FuelCostScore { get; set; }
        public Nullable<decimal> FuelCostScorePercentile { get; set; }
        public Nullable<double> InsuranceCostScore { get; set; }
        public Nullable<decimal> InsuranceCostScorePercentile { get; set; }
        public Nullable<double> DepreciationScore { get; set; }
        public Nullable<decimal> DepreciationScorePercentile { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public Nullable<decimal> TotalScorePercentile { get; set; }
        public Nullable<double> CarMDTotalScore { get; set; }
        public Nullable<decimal> CarMDTotalScorePercentile { get; set; }
        public Nullable<double> CompositeReliabilityScore { get; set; }
        public Nullable<decimal> CompositeReliabilityScorePercentile { get; set; }
        public Nullable<double> CompositeSafetyScore { get; set; }
        public Nullable<decimal> CompositeSafetyScorePercentile { get; set; }
        public Nullable<double> CompositeTCOScore { get; set; }
        public Nullable<decimal> CompositeTCOScorePercentile { get; set; }
    }
}
