//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictiveDiagnosticReportView
    {
        public string VehicleId { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string FixNameId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> AdditionalCost { get; set; }
        public Nullable<decimal> Labor { get; set; }
        public Nullable<decimal> PartsCost { get; set; }
        public int VehicleMileage { get; set; }
        public string Region { get; set; }
        public string EngineType { get; set; }
        public string VIN { get; set; }
        public string EngineVINCode { get; set; }
    }
}
