//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProRSFix
    {
        public string ProRSFixId { get; set; }
        public string UserId { get; set; }
        public string DiagnosticReportFixFeedbackId { get; set; }
        public string MilDtc { get; set; }
        public string FixId { get; set; }
        public string FixNameId { get; set; }
        public string Name { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_zh { get; set; }
        public string ProposedFixId { get; set; }
        public Nullable<bool> ProposedFixIdAccepted { get; set; }
        public Nullable<System.DateTime> ProposedFixIdAcceptedDateTimeUTC { get; set; }
        public string AdminUserId_ProposedFixIdAcceptedBy { get; set; }
        public int ProRSFixStatus { get; set; }
        public System.DateTime CreatedDateTimeUTC { get; set; }
    }
}
