//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleMaintenanceFixNameVehicle
    {
        public string ScheduleMaintenanceFixNameVehicleId { get; set; }
        public string ScheduleMaintenancePlanId { get; set; }
        public string ScheduleMaintenancePlanDetailId { get; set; }
        public string ScheduleMaintenanceServiceId { get; set; }
        public string FixNameId { get; set; }
        public string PolkVehicleYMMEId { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string EngineType { get; set; }
        public string EngineVinCode { get; set; }
        public string TrimLevel { get; set; }
        public string FixId { get; set; }
        public Nullable<bool> FixHasParts { get; set; }
        public Nullable<bool> FixHasLabor { get; set; }
    }
}
