//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateLaborRate
    {
        public string StateLaborRateId { get; set; }
        public string StateCode { get; set; }
        public Nullable<decimal> DollarsPerHour { get; set; }
        public string RegionName { get; set; }
        public Nullable<int> Currency { get; set; }
    }
}
