//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public string SymptomId { get; set; }
        public string SymptomFragmentIdType { get; set; }
        public string SymptomFragmentIdObservedEvent { get; set; }
        public string SymptomFragmentIdLocation { get; set; }
        public string SymptomFragmentIdOperationalCondition { get; set; }
        public string SymptomFragmentIdSurveyTechnicalInspection { get; set; }
        public string SymptomFragmentIdFixAssistDescription { get; set; }
        public string FixNameId { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
    }
}
