//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymptomFragment
    {
        public string SymptomFragmentId { get; set; }
        public Nullable<int> SymptomFragmentType { get; set; }
        public string SymptomFragmentValue { get; set; }
        public string SymptomFragmentLongValue { get; set; }
    }
}
