//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public string UserId { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailValidationCode { get; set; }
        public Nullable<bool> IsEmailValidated { get; set; }
        public Nullable<System.DateTime> EmailValidatedDateTimeUTC { get; set; }
        public string SignUpPromoCode { get; set; }
        public string SignUpPromoCodeOrderId { get; set; }
        public Nullable<int> AdditionalSessions { get; set; }
        public Nullable<int> AdditionalVehicles { get; set; }
        public Nullable<int> AdditionalDTCSearches { get; set; }
        public Nullable<int> AdditionalVINLookups { get; set; }
        public Nullable<int> AdditionalOpenReports { get; set; }
        public Nullable<int> AdditionalDailyReports { get; set; }
        public Nullable<int> UserType { get; set; }
        public string UserTypeExternalId { get; set; }
        public Nullable<int> UserAccountStatus { get; set; }
        public string UserAccountStatusSetByAdminUserId { get; set; }
        public Nullable<System.DateTime> UserAccountStatusSetDateTimeUTC { get; set; }
        public string DeclineReason { get; set; }
        public string ASECertifications { get; set; }
        public string ASECertificationsOther { get; set; }
        public string BusinessType { get; set; }
        public string JobPositionsString { get; set; }
        public string AutomobileMakesString { get; set; }
        public string AreasOfExpertiseString { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress1 { get; set; }
        public string ShopAddress2 { get; set; }
        public string ShopCity { get; set; }
        public string ShopRegion { get; set; }
        public string ShopPostCode { get; set; }
        public string ShopEmailAddress { get; set; }
        public string ShopPhoneNumber { get; set; }
        public string CompanyDescription { get; set; }
        public string BusinessTypeOther { get; set; }
        public string AreasOfExpertiseOther { get; set; }
        public string AutomobileMakeOther { get; set; }
        public Nullable<bool> IsProvidesRepairServicesToPublic { get; set; }
        public Nullable<bool> IsHadPreviousAccount { get; set; }
        public string JobPositionOther { get; set; }
        public Nullable<int> YearsExperience { get; set; }
        public string HowHearedAboutOBDFix { get; set; }
        public string HowHearedAboutOBDFixOther { get; set; }
        public string AboutMemberWhoReferredYou { get; set; }
        public string WhereTesterWasPurchased { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> ShowIdentityOnPostedComments { get; set; }
        public Nullable<bool> IsMasterTech { get; set; }
        public string MasterTechMakesString { get; set; }
        public Nullable<int> MasterTechNoFixReportsCap { get; set; }
        public Nullable<System.DateTime> MasterTechNoFixReportLastAssignedDateTimeUTC { get; set; }
        public Nullable<int> DTCSearchCount { get; set; }
        public Nullable<System.DateTime> DTCLastSearchDateTimeUTC { get; set; }
        public Nullable<int> VINLookupCount { get; set; }
        public Nullable<System.DateTime> VINLastLookupDateTimeUTC { get; set; }
        public Nullable<int> ReportCount { get; set; }
        public Nullable<System.DateTime> ReportLastCreatedDateTimeUTC { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> IsPaymentProgramAllowed { get; set; }
        public Nullable<bool> IsPaymentProgramMember { get; set; }
        public Nullable<System.DateTime> PaymentProgramStartDateTimeUTC { get; set; }
        public Nullable<bool> IsInOBDPromotion { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsInternal { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
        public string FullTextSearch { get; set; }
        public string PropertyDefinitionDataSetId { get; set; }
        public Nullable<bool> EnablePropertyDefinitionEditingOnForms { get; set; }
        public Nullable<int> Market { get; set; }
        public Nullable<bool> IsEncrypt { get; set; }
        public Nullable<bool> IsSystemAdministrator { get; set; }
        public Nullable<int> IsReceivesPastDueNoFixNotifications { get; set; }
        public Nullable<int> Permissions { get; set; }
        public Nullable<double> ValidationPayRateDollarsPerHour { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> EnablePropertyDefinitionEditingOnForms_copy1 { get; set; }
        public Nullable<int> ApplicationType { get; set; }
        public string ApplicationName { get; set; }
        public string LastLoginDateTimeUTC { get; set; }

        [ForeignKey("UserTypeExternalId")]
        [Required]
        public ExternalSystem ExternalSystem { get; set; }
    }
}
