//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTypeCode
    {
        public string VehicleTypeCodeId { get; set; }
        public Nullable<int> CodeId { get; set; }
        public string Title { get; set; }
        public string Title_es { get; set; }
        public string Title_fr { get; set; }
        public string Title_zh { get; set; }
        public string Conditions { get; set; }
        public string Conditions_es { get; set; }
        public string Conditions_fr { get; set; }
        public string Conditions_zh { get; set; }
        public string PossibleCauses { get; set; }
        public string PossibleCauses_es { get; set; }
        public string PossibleCauses_fr { get; set; }
        public string PossibleCauses_zh { get; set; }
        public Nullable<int> Trips { get; set; }
        public string MessageIndicatorLampFile { get; set; }
        public string TransmissionControlIndicatorLampFile { get; set; }
        public string PassiveAntiTheftIndicatorLampFile { get; set; }
        public string ServiceThrottleSoonIndicatorLampFile { get; set; }
        public string MonitorType { get; set; }
        public string MonitorFile { get; set; }
        public Nullable<int> IsDelmarCode { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> VehicleTypeCodeStatus { get; set; }
        public string CreatedDateTimeUTC { get; set; }
        public string UpdatedDateTimeUTC { get; set; }
        public Nullable<int> Title_esIsFromGoogle { get; set; }
    }
}
