//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTypeCodeAssignment
    {
        public string VehicleTypeCodeAssignmentId { get; set; }
        public string VehicleTypeId { get; set; }
        public string VehicleTypeCodeId { get; set; }
        public string ErrorCode { get; set; }
    }
}
