//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleWarrantyDetail
    {
        public string VehicleWarrantyDetailId { get; set; }
        public string VehicleWarrantyId { get; set; }
        public Nullable<int> WarrantyType { get; set; }
        public Nullable<int> MaxYears { get; set; }
        public Nullable<int> MaxMileage { get; set; }
        public string Notes { get; set; }
        public string Notes_es { get; set; }
        public string Notes_fr { get; set; }
        public string Notes_zh { get; set; }
    }
}
