//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        public string VehicleTypeId { get; set; }
        public Nullable<int> TCID { get; set; }
        public Nullable<int> Year { get; set; }
        public string ManufacturerName { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string BodyCode { get; set; }
        public string EngineType { get; set; }
        public string EngineVINCode { get; set; }
        public string EngineTypeVINLookup { get; set; }
        public string TransmissionControlType { get; set; }
        public string DLCLocation { get; set; }
        public string DLCAccess { get; set; }
        public string DLCComments { get; set; }
        public Nullable<int> IsDelmarVehicle { get; set; }
        public Nullable<int> IsActiveVehicle { get; set; }
        public Nullable<int> VehicleTypeStatus { get; set; }
        public string CreatedDateTimeUTC { get; set; }
        public string UpdatedDateTimeUTC { get; set; }
        public string FullTextSearch { get; set; }
    }
}
