//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Vehicle
    {
        public string VehicleId { get; set; }
        public string UserId { get; set; }
        public string VehicleTypeId { get; set; }
        public string ScheduleMaintenancePlanId { get; set; }
        public string Nickname { get; set; }
        public string Vin { get; set; }
        public string LicensePlateNumber { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerNameAlt { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string AAIA { get; set; }
        public string TrimLevel { get; set; }
        public string EngineVINCode { get; set; }
        public string EngineType { get; set; }
        public string FuelType { get; set; }
        public string TransmissionControlType { get; set; }
        public string VPManufacturer { get; set; }
        public Nullable<int> VPYear { get; set; }
        public string VPMake { get; set; }
        public string VPModel { get; set; }
        public string VPAAIA { get; set; }
        public string VPTrimLevel { get; set; }
        public string VPEngineVINCode { get; set; }
        public string VPEngineType { get; set; }
        public string VPFuelType { get; set; }
        public string VinPowerDatabaseVersion { get; set; }
        public Nullable<int> VinStatus { get; set; }
        public string VinStatusDescription { get; set; }
        public string DetailedDecodingProcessDescription { get; set; }
        public string PolkVehicleYMMEId { get; set; }
        public string PurchasedTsbsString { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<System.DateTime> MileageLastRecordedDateTimeUTC { get; set; }
        public Nullable<bool> SendScheduledMaintenanceAlerts { get; set; }
        public Nullable<int> ScheduleMaintenanceMileageIntervalLastFound { get; set; }
        public Nullable<System.DateTime> ScheduleMaintenanceAlertLastSentDateTimeUTC { get; set; }
        public Nullable<bool> SendNewRecallAlerts { get; set; }
        public Nullable<System.DateTime> NewRecallAlertLastSentDateTimeUTC { get; set; }
        public Nullable<bool> SendNewTSBAlerts { get; set; }
        public Nullable<System.DateTime> NewTSBAlertLastSentDateTimeUTC { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }

        [ForeignKey("UserId")]
        [Required]
        public User User { get; set; }

        [ForeignKey("PolkVehicleYMMEId")]
        [Required]
        public PolkVehicleYmme PolkVehicleYmme { get; set; }
    }
}
