//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayers.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleWarranty
    {
        public string VehicleWarrantyId { get; set; }
        public string Name { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_zh { get; set; }
        public Nullable<bool> IsTransferable { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<int> MinYear { get; set; }
        public Nullable<int> MaxYear { get; set; }
        public Nullable<bool> HasEngineTypeDefined { get; set; }
        public string EngineTypesString { get; set; }
        public Nullable<bool> HasEngineVINCodeDefined { get; set; }
        public string EngineVINCodesString { get; set; }
        public Nullable<bool> HasMakeDefined { get; set; }
        public string MakesString { get; set; }
        public Nullable<bool> HasModelDefined { get; set; }
        public string ModelsString { get; set; }
        public Nullable<bool> HasTrimLevelDefined { get; set; }
        public string TrimLevelsString { get; set; }
        public Nullable<bool> HasTransmissionDefined { get; set; }
        public string TransmissionsString { get; set; }
        public string AdminUserIdCreatedBy { get; set; }
        public string AdminUserIdUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdatedDateTimeUTC { get; set; }
        public string EngineType { get; set; }
    }
}
